spring:
  application:
    name: simple-app
  cloud:
    config:
      enabled: false

server:
  port: 8081  # Changed from 8080 to 8081

message: Hello from Local Development!

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always